### ISSUE TITLE
not working for cross realm players

### ISSUE THREAD

**Issue by ramteen85** [Limmek/Shitlist#1]
this needs to work for dungeon finder. which can include cross realm players in retail wow.
when i tried to add a player, it would save the player name under my own realm. 

for example i would add calswor-stormrage, but it would show up as calswor-frostmourne.
it would not let me manually edit the items as well.

Plus some of the menu options would not make sense.
need more flexible options such as setting the sound alarm.

A "sync with guild" option would be a great idea as well. 

Any chance we could work on this together as wow needs an addon like this really bad...

**Comment by Limmek** [comment]
Hi!

Thanks for the feedback!

This addon was made for wow classic from the beginning and then ported over to retail to after some requests.
The idea to make this addon came up when i was grouping up with idiots and did get tired of getting in the same party with the same dumb as'es all the time. I started to write down the player names but as the list did grow it did get hard to find the players names and in that moment i was thinking "_if there only where a addon to set a notice on players_". A few moments later and this addon was born.

I was doing a rewrite of the plugin but sadly one of my hard drives did fail, and of curse almost all my projects where saved on that drive except the tings i have saved here on github... 

The options where heavily changed. The drop down box where you select the player to edit it's info where changed to a clickable list instead and some other features.

About the cross realm issue. Somewhere in the new wow patches it has failed because i know it has worked as attended before. i did check this when ported it to retail. If i check my options i have players from different realms in my list.
This is something i will look in to.

"_sync with guild/friends_" is a very good idea and i did thought about to add it but i wanted to do a rewrite of the addon first.

Sure thing mate i'm glad if anyone could help me out with this since i do not have the time i used to have.

// Jim

**Comment by Limmek** [comment]
Closing this
